version: "3"

services:
  adminer:
    image: adminer
    restart: always
    networks:
      - app-network
    ports:
      - 8080:8080

  db:
    build:
      context: ./database
      dockerfile: DockerFile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: newsletter
      MYSQL_PASSWORD: newsletter
      MYSQL_DATABASE: newsletter
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network
    ports:
      - 3307:3306
    volumes:
      - ./database/data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: DockerFile
      target: development
    user: 1000:1000
    restart: unless-stopped
    command: npm run dev
    ports:
      - 5000:5000
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: DockerFile
      target: development
    restart: unless-stopped
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
