# Fetching Node 20
FROM node:22-alpine as development

# Declaring env
ENV NODE_ENV development

# Setting up the work directory
WORKDIR /usr/src/app

# Copying all the files in our project
COPY . .

# Installing dependencies
RUN npm install